//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo5_Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Localization_cshtml_fr123 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Views_Home_Localization_cshtml_fr123() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo5_Localization.Resources.Views.Home.Localization.cshtml.fr123", typeof(Views_Home_Localization_cshtml_fr123).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bonjour!.
        /// </summary>
        internal static string Hello_there__ {
            get {
                return ResourceManager.GetString("Hello there!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Salut {0,-10}! Vous êtes en {1:yyyy} an aujourd&apos;hui est {2}.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Apprenez à créer des applications ASP.NET qui peuvent fonctionner ne importe où..
        /// </summary>
        internal static string Learn_how_to_build_ASP_NET_apps_that_can_run_anywhere_ {
            get {
                return ResourceManager.GetString("Learn how to build ASP.NET apps that can run anywhere.", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to apprendre Encore Plus.
        /// </summary>
        internal static string Learn_More {
            get {
                return ResourceManager.GetString("Learn More", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to apprendre Encore Plus.
        /// </summary>
        internal static string LearnMore2 {
            get {
                return ResourceManager.GetString("LearnMore2", resourceCulture);
            }
        }
    }
}
